SYMBOL_NAMES = {
    "AAPL": "Apple Inc.",
    "ABNB": "Airbnb Inc.",
    "ADBE": "Adobe Inc.",
    "ADI": "Analog Devices Inc.",
    "ADP": "Automatic Data Processing Inc.",
    "ADSK": "Autodesk Inc.",
    "AEP": "American Electric Power Company Inc.",
    "ALNY": "Alnylam Pharmaceuticals Inc.",
    "AMAT": "Applied Materials Inc.",
    "AMD": "Advanced Micro Devices Inc.",
    "AMGN": "Amgen Inc.",
    "AMZN": "Amazon.com Inc.",
    "APP": "AppLovin Corporation",
    "ARM": "Arm Holdings plc",
    "ASML": "ASML Holding N.V.",
    "AVGO": "Broadcom Inc.",
    "AXON": "Axon Enterprise Inc.",
    "BKNG": "Booking Holdings Inc.",
    "BKR": "Baker Hughes Company",
    "CCEP": "Coca-Cola Europacific Partners PLC",
    "CDNS": "Cadence Design Systems Inc.",
    "CEG": "Constellation Energy Corporation",
    "CHTR": "Charter Communications Inc.",
    "CMCSA": "Comcast Corporation",
    "COST": "Costco Wholesale Corporation",
    "CPRT": "Copart Inc.",
    "CRWD": "CrowdStrike Holdings Inc.",
    "CSCO": "Cisco Systems Inc.",
    "CSGP": "CoStar Group Inc.",
    "CSX": "CSX Corporation",
    "CTAS": "Cintas Corporation",
    "CTSH": "Cognizant Technology Solutions Corporation",
    "DASH": "DoorDash Inc.",
    "DDOG": "Datadog Inc.",
    "DXCM": "DexCom Inc.",
    "EA": "Electronic Arts Inc.",
    "EXC": "Exelon Corporation",
    "FANG": "Diamondback Energy Inc.",
    "FAST": "Fastenal Company",
    "FTNT": "Fortinet Inc.",
    "GEHC": "GE HealthCare Technologies Inc.",
    "GILD": "Gilead Sciences Inc.",
    "GOOG": "Alphabet Inc. Class C",
    "GOOGL": "Alphabet Inc. Class A",
    "HON": "Honeywell International Inc.",
    "IDXX": "IDEXX Laboratories Inc.",
    "INSM": "Insmed Incorporated",
    "INTC": "Intel Corporation",
    "INTU": "Intuit Inc.",
    "ISRG": "Intuitive Surgical Inc.",
    "KDP": "Keurig Dr Pepper Inc.",
    "KHC": "The Kraft Heinz Company",
    "KLAC": "KLA Corporation",
    "LRCX": "Lam Research Corporation",
    "MAR": "Marriott International Inc.",
    "MCHP": "Microchip Technology Incorporated",
    "MDLZ": "Mondelez International Inc.",
    "MELI": "MercadoLibre Inc.",
    "META": "Meta Platforms Inc.",
    "MNST": "Monster Beverage Corporation",
    "MPWR": "Monolithic Power Systems Inc.",
    "MRVL": "Marvell Technology Inc.",
    "MSFT": "Microsoft Corporation",
    "MSTR": "Strategy Inc.",
    "MU": "Micron Technology Inc.",
    "NFLX": "Netflix Inc.",
    "NVDA": "NVIDIA Corporation",
    "NXPI": "NXP Semiconductors N.V.",
    "ODFL": "Old Dominion Freight Line Inc.",
    "ORLY": "O'Reilly Automotive Inc.",
    "PANW": "Palo Alto Networks Inc.",
    "PAYX": "Paychex Inc.",
    "PCAR": "PACCAR Inc.",
    "PDD": "PDD Holdings Inc.",
    "PEP": "PepsiCo Inc.",
    "PLTR": "Palantir Technologies Inc.",
    "PYPL": "PayPal Holdings Inc.",
    "QCOM": "QUALCOMM Incorporated",
    "REGN": "Regeneron Pharmaceuticals Inc.",
    "ROP": "Roper Technologies Inc.",
    "ROST": "Ross Stores Inc.",
    "SBUX": "Starbucks Corporation",
    "SHOP": "Shopify Inc.",
    "SNPS": "Synopsys Inc.",
    "STX": "Seagate Technology Holdings plc",
    "TEAM": "Atlassian Corporation",
    "TMUS": "T-Mobile US Inc.",
    "TSLA": "Tesla Inc.",
    "TTWO": "Take-Two Interactive Software Inc.",
    "TXN": "Texas Instruments Incorporated",
    "VRSK": "Verisk Analytics Inc.",
    "VRTX": "Vertex Pharmaceuticals Incorporated",
    "WDAY": "Workday Inc.",
    "WDC": "Western Digital Corporation",
    "XEL": "Xcel Energy Inc.",
    "ZS": "Zscaler Inc.",
    "WBD": "Warner Bros. Discovery Inc.",
}
